name: Industriekommentare
description: "Kommentare für Änderungsvoschläge der Industrie"
title: "[Änderungsvorschlag]: "
projects: "gematik-poc/projects/1"
assignees: 
  - mwatzek
body:
  - type: markdown
    attributes:
      value: |
        Geben Sie hier die Daten für Ihren Verbesserungsvorschlag ein
  - type: dropdown
    id: kind
    attributes:
      label: Art der Änderung
      description: Welcher Art ist Ihr Änderungsvorschlag 
      options:
        - Fehler
        - Verbesserung
        - Ergänzung
      default: 0
    validations:
      required: true
  - type: input
    id: document
    attributes:
      label: "Dokument"
      description: "Name des Dokuments (erforderlich)"
    validations:
      required: true
  - type: input
    id: chapter
    attributes:
      label: "Kapitel"
      description: "Name des Kapitels im Dokument"
    validations:
      required: false
  - type: input
    id: afo
    attributes:
      label: "AFO"
      description: "AFO im Dokument"
    validations:
      required: false
  - type: input
    id: link
    attributes:
      label: "Link"
      description: "Link zu Dokument/Kapitel/AFO"
    validations:
      required: false
  - type: input
    id: line
    attributes:
      label: "Zeilennr."
      description: "Zeilennr. im Dokument"
    validations:
      required: false
  - type: textarea
    id: suggestion
    attributes:
      label: "Vorschlag"
      description: "Ihr Änderungsvorschlag (erforderlich)"
    validations:
      required: true
