name: Industriekommentare
description: "Kommentare für Änderungsvoschläge der Industrie"
title: "[Änderungsvorschlag]: "
labels: ["Offen"]
projects: ["gematik-poc/1"]
assignees: ["mwatzek"]
body:
  - type: markdown
    attributes:
      value: |
        Geben Sie hier die Daten für Ihren Verbesserungsvorschlag ein
  - type: input
    id: organization
    attributes:
      label: "Organisation"
      description: "Name Ihrer Organisation (erforderlich)"
    validations:
      required: true
- type: dropdown
    id: kind
    attributes:
      label: Fehlerkategorie
      description: Wählen Sie die Fehlerkategorie Ihres Änderungsvorschlags aus 
      options:
        - Alles auswählen
        - FF
        - M
      default: 0
    validations:
      required: true
  - type: dropdown
    id: topic
    attributes:
      label: Thema
      description: Wählen Sie das Thema Ihres Änderungsvorschlags aus 
      options:
        - Alles auswählen
        - betrifft ePA
        - betrifft E-Rezept
      default: 0
    validations:
      required: false
  - type: input
    id: document
    attributes:
      label: "Dokument"
      description: "Name des Dokuments (erforderlich)"
    validations:
      required: true
  - type: input
    id: chapter
    attributes:
      label: "Kapitel"
      description: "Name des Kapitels im Dokument"
    validations:
      required: false
  - type: input
    id: afo
    attributes:
      label: "AFO"
      description: "AFO im Dokument"
    validations:
      required: false
  - type: input
    id: link
    attributes:
      label: "Link"
      description: "Link zu Dokument/Kapitel/AFO"
    validations:
      required: false
  - type: input
    id: line
    attributes:
      label: "Zeilennr."
      description: "Zeilennr. im Dokument"
    validations:
      required: false
  - type: textarea
    id: proposal
    attributes:
      label: "Änderungsvorschlag"
      description: "Kommentar und Änderungsvorschlag (erforderlich)"
    validations:
      required: true
